#!/usr/bin/env bash
# Install git hooks for Alpha Manager.
#
# Currently installs one pre-commit hook that enforces the docs/ layout
# invariants defined in scripts/check_docs.py.
#
# Idempotent: re-running this script overwrites the hook with the latest
# version. Safe to run any time.
#
# Usage:  ./scripts/install_hooks.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_DIR="${REPO_ROOT}/.git/hooks"
HOOK_PATH="${HOOK_DIR}/pre-commit"
CHECK_SCRIPT="${REPO_ROOT}/scripts/check_docs.py"

if [[ ! -d "${REPO_ROOT}/.git" ]]; then
    echo "install_hooks.sh: not inside a git repository at ${REPO_ROOT}" >&2
    exit 1
fi

if [[ ! -f "${CHECK_SCRIPT}" ]]; then
    echo "install_hooks.sh: missing ${CHECK_SCRIPT}" >&2
    exit 1
fi

mkdir -p "${HOOK_DIR}"

# Write a tiny wrapper so contributors can see what's going on and so the
# hook keeps working if check_docs.py is moved (we locate it dynamically).
cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env bash
# Alpha Manager pre-commit hook — enforces docs/ layout invariants.
# Generated by scripts/install_hooks.sh. Re-run that script to update.
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec python3 "${REPO_ROOT}/scripts/check_docs.py"
HOOK

chmod +x "${HOOK_PATH}"
chmod +x "${CHECK_SCRIPT}"

echo "Installed pre-commit hook at ${HOOK_PATH}"
echo "It runs: python3 scripts/check_docs.py"
